{{- if and .Values.database.mysql.dsn (not .Values.database.mysql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loopd.databaseSecretName" . }}
  labels:
    {{- include "loopd.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
  {{ .Values.database.mysql.existingSecretKey }}: {{ .Values.database.mysql.dsn | quote }}
{{- end }}
